import { ApiProperty } from '@nestjs/swagger';
import { DocumentResultDto } from './document-result.dto';

export class QueryResponseDto {
  @ApiProperty({
    description: 'Original query',
    example: 'What is Node.js?',
  })
  query: string;

  @ApiProperty({
    description: 'Relevant documents found',
    type: [DocumentResultDto],
  })
  documents: DocumentResultDto[];

  @ApiProperty({
    description: 'Answer generated by LLM based on documents',
    example: 'Based on the documents found, here is the relevant context:\n\nNode.js is a JavaScript platform...',
  })
  answer: string;
}



